from agents.types_.context import SharedContext
from agents.utils.gemini_client import gemini
from agents.utils.llm_client import langfuse
from agents.utils.prompt_engine import build_prompt
from agents.utils.database import update_db_and_status

def backend_node(state: SharedContext) -> SharedContext:
    # ... Tracing logic remains same ...
    trace = langfuse.trace(name=f"Project: {state.project}", id=state.trace_id)
    span = trace.span(name="Backend Generation")

    update_db_and_status(run_id=state.project, status="running")
    print(f"\n[NODE: BACKEND] 🚀 Writing code with Gemini Flash...")

    system_prompt = build_prompt("backend_agent", state)

    user_request = (
        f"You are a senior software engineer. Generate production-quality code.\n"
        f"Tech Stack: {state.tech_stack}\n"
        f"Conventions: {state.conventions}\n"
        f"API Routes to implement: {list(state.api_routes.keys()) if state.api_routes else ['default']}\n"
        f"Entities: {list(state.entities.keys()) if state.entities else ['default']}\n\n"
        f"Prefix each file with a comment: // FILE: path/to/filename.ts\n"
        f"Generate complete, working code. Do not use placeholders."
    )

    try:
        response = gemini.generate_code(
            system_prompt=system_prompt,
            user_message=user_request
        )

        # Clear code on first attempt, use fresh code each loop
        new_code = f"/* Iteration {state.loop_count} — Generated by Gemini 2.0 Flash */\n{response['text']}"
        state.generated_code = new_code

        state.token_usage["input"] += response.get("input_tokens", 0)
        state.token_usage["output"] += response.get("output_tokens", 0)

        update_db_and_status(run_id=state.project, status="running", code=state.generated_code)
        span.end(output={"tokens_used": response.get("output_tokens", 0)})

    except Exception as e:
        print(f"[NODE: BACKEND] ❌ Error: {str(e)}")
        state.risk_level = "high"
        span.end(level="ERROR", status_message=str(e))

    return state