"use client";

import { ChevronRight, FileCode2, Terminal, Layers } from "lucide-react";
import { useState } from "react";
import FileTree, { FileNode } from "@/components/ui/file-tree-1";

const projectStructure: FileNode[] = [
  {
    id: "root",
    name: "craftastudio-workspace",
    type: "folder",
    children: [
      {
        id: "block-auth",
        name: "BLK-AUTH-01 (Authentication)",
        type: "folder",
        children: [
          { id: "auth-middleware", name: "middleware.ts", type: "file" },
          { id: "auth-route", name: "route.ts", type: "file" },
          { id: "auth-schema", name: "schema.ts", type: "file" },
        ],
      },
      {
        id: "block-db",
        name: "BLK-DB-02 (Database)",
        type: "folder",
        children: [
          { id: "db-prisma", name: "schema.prisma", type: "file" },
          { id: "db-client", name: "db.ts", type: "file" },
          { id: "db-seed", name: "seed.ts", type: "file" },
        ],
      },
      {
        id: "block-ui",
        name: "BLK-UI-03 (Frontend)",
        type: "folder",
        children: [
          { id: "ui-layout", name: "layout.tsx", type: "file" },
          { id: "ui-page", name: "page.tsx", type: "file" },
          { id: "ui-styles", name: "globals.css", type: "file" },
        ],
      },
      { id: "readme", name: "README.md", type: "file" },
      { id: "package", name: "package.json", type: "file" },
    ],
  },
];

const mockCodeMap: Record<string, string> = {
  "auth-middleware": `import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/request';

export function middleware(request: NextRequest) {
  const token = request.cookies.get('token');
  
  if (!token && !request.nextUrl.pathname.startsWith('/login')) {
    return NextResponse.redirect(new URL('/login', request.url));
  }
  
  return NextResponse.next();
}`,
  "db-prisma": `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}`,
  "readme": `# CraftaStudio Project
  
This project was generated by CraftaStudio AI.

## Structure
- BLK-AUTH-01: Authentication Logic
- BLK-DB-02: Database Schema
- BLK-UI-03: Frontend Application`,
};

export function CodeTab() {
  const [selectedFile, setSelectedFile] = useState<FileNode | null>({ id: "auth-middleware", name: "middleware.ts", type: "file" });
  const [codeContent, setCodeContent] = useState<string>(mockCodeMap["auth-middleware"]);

  const handleSelect = (node: FileNode) => {
    if (node.type === "file") {
      setSelectedFile(node);
      setCodeContent(mockCodeMap[node.id] || `// Content for ${node.name}\n// Generated by CraftaStudio`);
    }
  };

  return (
    <div className="w-full h-full flex bg-[var(--background)] animate-in fade-in duration-500">
      {/* Sidebar - File Explorer */}
      <div className="w-[280px] shrink-0 border-r border-[var(--border)] bg-[var(--surface)]/30 flex flex-col h-full">
        <div className="p-4 flex items-center justify-between border-b border-[var(--border)]">
          <div className="flex items-center gap-2">
            <Terminal size={14} className="text-[#ccee66]" />
            <span className="text-[11px] font-bold tracking-widest uppercase text-[var(--muted-foreground)]">Explorer</span>
          </div>
          <Layers size={14} className="text-[var(--muted-foreground)]" />
        </div>
        
        <div className="flex-1 overflow-y-auto p-2 scrollbar-hide">
          <FileTree 
            data={projectStructure} 
            defaultExpanded={{ "root": true, "block-auth": true }}
            onSelect={handleSelect}
            selectedId={selectedFile?.id}
          />
        </div>
      </div>

      {/* Editor Main */}
      <div className="flex-1 flex flex-col h-full overflow-hidden">
        {/* Editor Controls / Tabs */}
        <div className="h-11 border-b border-[var(--border)] flex items-center px-4 shrink-0 bg-[var(--surface)]/20 justify-between">
          <div className="flex items-center gap-2 overflow-hidden">
            <span className="text-[10px] font-mono text-[var(--muted-foreground)] uppercase tracking-tighter shrink-0">Workspace</span>
            <ChevronRight className="size-3 text-[var(--muted-foreground)]" />
            <div className="flex items-center gap-2 text-white overflow-hidden">
              <span className="text-[12px] font-medium truncate">{selectedFile?.name || "Select a file"}</span>
            </div>
          </div>

          <div className="flex items-center gap-3">
             <div className="flex items-center gap-1.5 px-2 py-1 rounded bg-[#ccee66]/5 border border-[#ccee66]/20">
                <div className="size-1.5 rounded-full bg-[#ccee66] animate-pulse" />
                <span className="text-[10px] font-bold text-[#ccee66]">SYNCED</span>
             </div>
          </div>
        </div>

        {/* Code Content (Editable Area) */}
        <div className="flex-1 overflow-hidden bg-[var(--code-bg)] flex flex-col relative text-[var(--code-text)]">
          {/* Subtle vignette background effect */}
          <div className="absolute inset-0 pointer-events-none bg-[radial-gradient(circle_at_50%_0%,rgba(204,238,102,0.03),transparent_70%)] opacity-30" />

          <div className="flex-1 overflow-auto flex font-mono text-sm leading-relaxed text-[var(--code-text)]">
            {/* Real Line Numbers */}
            <div className="w-12 shrink-0 border-r border-[var(--code-border)] flex flex-col items-end pr-4 py-6 text-zinc-500 bg-[var(--code-gutter)] select-none text-[12px]">
              {codeContent.split('\n').map((_, i) => (
                <span key={i} className="leading-[1.6]">{i + 1}</span>
              ))}
            </div>
            
            <textarea
              value={codeContent}
              onChange={(e) => setCodeContent(e.target.value)}
              spellCheck={false}
              className="flex-1 bg-transparent text-[var(--code-text)] p-6 resize-none outline-none leading-[1.6] text-[13px] tracking-tight selection:bg-[var(--primary-accent)]/20"
            />
          </div>
          
          {/* Editor Status Bar Overlay */}
          <div className="h-6 border-t border-[var(--code-border)] bg-[var(--code-gutter)] flex items-center px-4 justify-between shrink-0">
             <div className="flex items-center gap-4 text-[10px] text-zinc-500 font-mono">
               <span>UTF-8</span>
               <span>TypeScript</span>
             </div>
             <div className="flex items-center gap-4 text-[10px] text-zinc-500 font-mono">
               <span>Ln {codeContent.split('\n').length}, Col 1</span>
               <span>Spaces: 2</span>
             </div>
          </div>
        </div>
      </div>
    </div>
  );
}
